site_name: johnjuly的笔记本
site_url: https://johnjuly.github.io/mynote/
repo_name: johnjuly/mynote
repo_url: https://github.com/johnjuly/mynote/
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - attr_list
  - md_in_html
  

nav:
  - Home:
    - index.md
  - Thinking:
    - maxism: thinking/maxism.md
    - lit: thinking/dy.md
  - Art:
    - music theory: art/music theory.md
    - design book: art/design book.md
  - CS:
    - 网络: cs/net.md
    - 数据结构与算法: cs/dsa.md
    - verilog: cs/verilog.md
  - others:
    - examole.md

  