site_name: johnjuly的笔记本
site_url: https://johnjuly.github.io/mynote/
repo_name: johnjuly/mynote
repo_url: https://github.com/johnjuly/mynote/
edit_uri: edit/main/docs/

use_directory_urls: false # 加上这句后才能显示用 html img 相对路径插入的图片

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font:
    text: Noto Serif SC # Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  # for code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true #内容选项卡

nav:
  - Home:
      - index.md
  - Thinking:
      - maxism: thinking/maxism.md
      - lit: thinking/dy.md
  - Art:
      - music theory: art/music theory.md
      - design book: art/design book.md
  - iot:
      - 感知技术与应用: iot/sensor.md
  - CS:
      - 网络: cs/net.md
      - 数据结构与算法: cs/language/c++/dsa.md
      - 嵌入式系统:
          - cs/embeded systen/embedded.0.md
          - cs/embeded systen/embeded.md
      - 软件安全:
          - cs/软件安全/review.md

      - 人工智能:
          - cs/人工智能/search .md
          - cs/人工智能/cs188 probability.md
          - cs/人工智能/review.md

      - 数据库系统:
          - cs/db/1.md
          - cs/db/sql.md
          - cs/db/sql2.md

      - 计算机系统:
          - cs/计算机系统/计算机系统概论.md
          - cs/计算机系统/计组review.md
      - 工具:
          - cs/tools/git.md
          - the missing semester:
              - cs/tools/the missing semaster/shell.md
              - cs/tools/the missing semaster/shell tools and scripts.md
      - c++学习:
          - hj:
              - cs/language/c++/hj/c++ 1.md
              - cs/language/c++/hj/c++ 2.md
          - cs106l:
              - cs/language/c++/cs106l/types and structs.md
              - cs/language/c++/cs106l/template functions.md
              - cs/language/c++/cs106l/template classes.md
              - cs/language/c++/cs106l/streams.md
              - cs/language/c++/cs106l/operatoroverloading.md
              - cs/language/c++/cs106l/iterators.md
              - cs/language/c++/cs106l/initialization and references .md
              - cs/language/c++/cs106l/functions and lambdas.md
              - cs/language/c++/cs106l/classes.md
              - cs/language/c++/cs106l/containers.md

          - c++2-2:
              - cs/language/c++/c++2-2/datastructure.md
              - cs/language/c++/c++2-2/projectrecord.md
              - cs/language/c++/c++2-2/wxwidgets.md
              - cs/language/c++/c++2-2/cppexercise.md
              - cs/language/c++/c++2-2/听课记录.md
      - python: cs/language/python/python.md
      - verilog: cs/language/assembly/verilog.md

      - 汇编语言: cs/language/sssembly/assembly language.md

  - read:
      - csapp: read/csapprnote1.md

  - others:
      - examole.md
